\set ON_ERROR_STOP on

DO $$ BEGIN
  CREATE ROLE amas_app LOGIN;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE ROLE amas_readonly LOGIN;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO amas_app, amas_readonly', current_database());
END $$;
GRANT USAGE ON SCHEMA amas TO amas_app, amas_readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA amas TO amas_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA amas TO amas_app;
GRANT SELECT ON ALL TABLES IN SCHEMA amas TO amas_readonly;

ALTER DEFAULT PRIVILEGES IN SCHEMA amas
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO amas_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA amas
  GRANT USAGE, SELECT ON SEQUENCES TO amas_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA amas
  GRANT SELECT ON TABLES TO amas_readonly;
